### Reading the image file

In [ ]:
# pip install opencv-python
# pip install opencv-contrib-python

In [1]:
import cv2

In [2]:
cv2.imread?

In [3]:
pwd

'/Users/aniket/Desktop/Jupyter Notebook/NLP_OpenCV/OpenCV Codes'

In [4]:
# loading and converting the image into numpy array
# printing the corresponding values
image = cv2.imread("DATA/cat.jpeg")

In [5]:
image

array([[[16, 15, 11],
        [23, 22, 18],
        [31, 30, 26],
        ...,
        [ 7,  8,  6],
        [ 7,  8,  6],
        [ 7,  8,  6]],

       [[15, 14, 10],
        [22, 21, 17],
        [30, 29, 25],
        ...,
        [ 6,  7,  5],
        [ 6,  7,  5],
        [ 6,  7,  5]],

       [[14, 13,  9],
        [21, 20, 16],
        [30, 29, 25],
        ...,
        [ 6,  7,  5],
        [ 6,  7,  5],
        [ 6,  7,  5]],

       ...,

       [[ 8,  8,  8],
        [ 7,  7,  7],
        [ 5,  5,  5],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 9,  9,  9],
        [ 8,  8,  8],
        [ 6,  6,  6],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[10, 10, 10],
        [ 9,  9,  9],
        [ 7,  7,  7],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=uint8)

In [6]:
image.shape

(350, 528, 3)

In [7]:
350 * 528 * 3

554400

In [8]:
4000 * 4000 * 3 * 100000 

4800000000000

In [9]:
32 * 32 * 3 * 100000

307200000

In [10]:
print("width : {}".format(image.shape[1]))
print("height : {}".format(image.shape[0]))
print("channels : {}".format(image.shape[2]))

width : 528
height : 350
channels : 3


In [15]:
# load image into cv2 window
# wait for key press
# write image into another format
cv2.imshow("output", image)
cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
cv2.destroyAllWindows()

## writing the images to file

In [17]:
pwd

'/Users/aniket/Desktop/Jupyter Notebook/NLP_OpenCV/OpenCV Codes'

In [18]:
cv2.imwrite("new_catasdfasd.jpg", image)

True

In [19]:
!dir

zsh:1: command not found: dir


### Get and Set 

In [20]:
image = cv2.imread("DATA/cat.jpeg")

In [21]:
cv2.imshow("my asdfas image", image)
cv2.waitKey()
cv2.destroyAllWindows()

In [22]:
cv2.destroyAllWindows()

In [ ]:
image[0,0]

In [29]:
image[1:4,1:4]

array([[[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]], dtype=uint8)

In [30]:
# grab the 0,0 pixel of the image and print color values
(b, g, r) = image[1:4,1:4]

In [31]:
print("Pixel at (0,0) - Red:{} Green:{} Blue:{}".format(r,g,b))

Pixel at (0,0) - Red:[[  0   0 255]
 [  0   0 255]
 [  0   0 255]] Green:[[  0   0 255]
 [  0   0 255]
 [  0   0 255]] Blue:[[  0   0 255]
 [  0   0 255]
 [  0   0 255]]


In [32]:
# change the color of the pixel at 0,0 and print again
image[0:100,0:100] = (0,0,255)
(b,g,r) = image[1:4,1:4]
print("Pixel at (0,0) - Red: {}, Green: {}, Blue: {}".format(r,g,b))

Pixel at (0,0) - Red: [[  0   0 255]
 [  0   0 255]
 [  0   0 255]], Green: [[  0   0 255]
 [  0   0 255]
 [  0   0 255]], Blue: [[  0   0 255]
 [  0   0 255]
 [  0   0 255]]


In [33]:
cv2.imshow("output", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [34]:
cv2.destroyAllWindows()

In [35]:
# grab the region and show in cv2 window
corner = image[0:100, 0:100] # [y:height , x:width  ]

In [36]:
corner.shape

(100, 100, 3)

In [37]:
cv2.imshow("corner image", corner)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [38]:
# change color of the area of image
image[0:100, 0:100] = (0,0,0)

In [39]:
image.shape

(350, 528, 3)

In [40]:
cv2.imshow("Color area changed", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
# change the color of the pixel at 0,0 and print again
image[:20, : ] = (18,255,180)


In [42]:
cv2.imshow("Color area changed", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
 1+1 

2